# Harmony Jekyll theme general configurations

# Base URL
baseurl: #/jackmilano.github.io #/harmony

# Site live URL
url: http://jackmilano.github.io

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: jackMilano.github.io #Harmony
  # Little description about your site
  description: Giacomo Milano's github page.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
   This is the personal website of Giacomo Milano,
   developer, game designer, open minded.
  basetheme: theme-base-01 # pre defined themes are darken, blue-water, redish.
  author: # Author details
    name: Giacomo Milano
    email: giacomomilano89@gmail.com
    url: http://jackmilano.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-61355481-1

  # Profile links, leave blank to ignore
  social:
    facebook:
    github: jackMilano
    gplus: +GiacomoMilano89
    linkedin: giacomomilano
    pinterest:
    twitter: Giacomo_Milano
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
# markdown:    kramdown
# kramdown:
#   input: GFM
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - Rakefile
  - README.md
  - .sass-cache

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed #nested, expanded, compact, compressed

# Time Zone
timezone: Europe/Rome

# Front Matter YAML defaults
defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      author: "Giacomo Milano"
      # published: "false"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # category: "blog"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      category: "about"

safe: true    # disable custom plugins, and ignore symbolic links
future: false # future posts won't be published

fb_og: true   # enable Facebook OpenGraph (http://ogp.me)
